# Generated by Django 5.1.1 on 2024-10-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAppApi', '0002_expense_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
