# Generated by Django 5.1.1 on 2024-10-18 04:46

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAppApi', '0003_alter_expense_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='frequency',
        ),
        migrations.AddField(
            model_name='expense',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 22, 45, 44, 133689)), default=11.244444444444445, size=None),
            preserve_default=False,
        ),
    ]
