# Generated by Django 5.1.1 on 2024-10-18 04:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAppApi', '0004_remove_expense_created_at_remove_expense_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None),
        ),
    ]
