# Generated by Django 5.1.1 on 2024-10-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAppApi', '0005_alter_expense_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dates',
            field=models.JSONField(),
        ),
    ]
